version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}

      - run: ./gradlew downloadDependencies --daemon
      - save_cache:
          key: gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run:
          name: Run Unit Tests
          command: ./gradlew test --daemon
      - run:
          name: Run Integration Tests
          command: ./gradlew integrationTest --daemon
workflows:
  version: 2
  build_and_test:
    jobs:
      - test