REM MSSQL CONFIGURATION BLOCK

SETX CONN_URI_MSSQL ""
SETX CONN_USER_MSSQL ""
SETX CONN_PASSWORD_MSSQL ""
SETX CONN_DBNAME_MSSQL ""
SETX CONN_HOST_MSSQL ""


REM MYSQL CONFIGURATION BLOCK

SETX CONN_URI_MYSQL ""
SETX CONN_USER_MYSQL ""
SETX CONN_PASSWORD_MYSQL ""
SETX CONN_DBNAME_MYSQL ""
SETX CONN_HOST_MYSQL ""


REM ORACLE CONFIGURATION BLOCK

SETX CONN_URI_ORACLE ""
SETX CONN_USER_ORACLE ""
SETX CONN_PASSWORD_ORACLE ""
SETX CONN_DBNAME_ORACLE ""
SETX CONN_HOST_ORACLE ""


REM POSTGRESQL CONFIGURATION BLOCK

SETX CONN_URI_POSTGRESQL ""
SETX CONN_USER_POSTGRESQL ""
SETX CONN_PASSWORD_POSTGRESQL ""
SETX CONN_DBNAME_POSTGRESQL ""
SETX CONN_HOST_POSTGRESQL ""